[package]
name = "asta-campus-desktop"
version = "2.0.0"
description = "Asta Campus - Plateforme Académique & Sécurisée UNASMOH"
authors = ["Christian Alvaro <christian7alvaro@gmail.com>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
asta-core = { path = "../crates/asta-core" }
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
